# Generated by Django 4.2.1 on 2023-05-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserAuthor',
        ),
    ]
