# Generated by Django 4.2.1 on 2023-05-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NoName_Article', max_length=50, verbose_name='Name')),
                ('anons', models.CharField(default='NoName_Announcement', max_length=250, verbose_name='Announcement')),
                ('full_text', models.TextField(verbose_name='Article')),
                ('date', models.DateTimeField(verbose_name='Publication date')),
            ],
        ),
    ]
